// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwqZFSmYQyOMcuk0zcMaPdx90qAKCIOOg',
    appId: '1:797531249979:android:507ca624c4d8bcf2b6eb1e',
    messagingSenderId: '797531249979',
    projectId: 'fir-signin-1580a',
    storageBucket: 'fir-signin-1580a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfVaYV5fTtI8CBIeHe6KKziSNsQH2ZRbk',
    appId: '1:797531249979:ios:b7a86d82c940f4a2b6eb1e',
    messagingSenderId: '797531249979',
    projectId: 'fir-signin-1580a',
    storageBucket: 'fir-signin-1580a.appspot.com',
    androidClientId: '797531249979-0khq4llv3h714oche5vn6ghh2b37lj97.apps.googleusercontent.com',
    iosClientId: '797531249979-djcl69do3lmrkakoktl636ssirdgghie.apps.googleusercontent.com',
    iosBundleId: 'com.example.jsonHandling',
  );
}
